<?php

# GENERATED, LOOK AT create_autoloader_decimal_sub.php 

namespace Tg\Decimal;

function decimal0(string $value) { return new \Tg\Decimal\Decimal($value, 0); }
function decimal1(string $value) { return new \Tg\Decimal\Decimal($value, 1); }
function decimal2(string $value) { return new \Tg\Decimal\Decimal($value, 2); }
function decimal3(string $value) { return new \Tg\Decimal\Decimal($value, 3); }
function decimal4(string $value) { return new \Tg\Decimal\Decimal($value, 4); }
function decimal5(string $value) { return new \Tg\Decimal\Decimal($value, 5); }
function decimal6(string $value) { return new \Tg\Decimal\Decimal($value, 6); }
function decimal7(string $value) { return new \Tg\Decimal\Decimal($value, 7); }
function decimal8(string $value) { return new \Tg\Decimal\Decimal($value, 8); }
function decimal9(string $value) { return new \Tg\Decimal\Decimal($value, 9); }
function decimal10(string $value) { return new \Tg\Decimal\Decimal($value, 10); }
function decimal11(string $value) { return new \Tg\Decimal\Decimal($value, 11); }
function decimal12(string $value) { return new \Tg\Decimal\Decimal($value, 12); }
function decimal13(string $value) { return new \Tg\Decimal\Decimal($value, 13); }
function decimal14(string $value) { return new \Tg\Decimal\Decimal($value, 14); }
function decimal15(string $value) { return new \Tg\Decimal\Decimal($value, 15); }
function decimal16(string $value) { return new \Tg\Decimal\Decimal($value, 16); }
function decimal17(string $value) { return new \Tg\Decimal\Decimal($value, 17); }
function decimal18(string $value) { return new \Tg\Decimal\Decimal($value, 18); }
function decimal19(string $value) { return new \Tg\Decimal\Decimal($value, 19); }
function decimal20(string $value) { return new \Tg\Decimal\Decimal($value, 20); }
function decimal21(string $value) { return new \Tg\Decimal\Decimal($value, 21); }
function decimal22(string $value) { return new \Tg\Decimal\Decimal($value, 22); }
function decimal23(string $value) { return new \Tg\Decimal\Decimal($value, 23); }
function decimal24(string $value) { return new \Tg\Decimal\Decimal($value, 24); }
function decimal25(string $value) { return new \Tg\Decimal\Decimal($value, 25); }
function decimal26(string $value) { return new \Tg\Decimal\Decimal($value, 26); }
function decimal27(string $value) { return new \Tg\Decimal\Decimal($value, 27); }
function decimal28(string $value) { return new \Tg\Decimal\Decimal($value, 28); }
function decimal29(string $value) { return new \Tg\Decimal\Decimal($value, 29); }
function decimal30(string $value) { return new \Tg\Decimal\Decimal($value, 30); }
function decimal31(string $value) { return new \Tg\Decimal\Decimal($value, 31); }
function decimal32(string $value) { return new \Tg\Decimal\Decimal($value, 32); }
function decimal33(string $value) { return new \Tg\Decimal\Decimal($value, 33); }
function decimal34(string $value) { return new \Tg\Decimal\Decimal($value, 34); }
function decimal35(string $value) { return new \Tg\Decimal\Decimal($value, 35); }
function decimal36(string $value) { return new \Tg\Decimal\Decimal($value, 36); }
function decimal37(string $value) { return new \Tg\Decimal\Decimal($value, 37); }
function decimal38(string $value) { return new \Tg\Decimal\Decimal($value, 38); }
function decimal39(string $value) { return new \Tg\Decimal\Decimal($value, 39); }
function decimal40(string $value) { return new \Tg\Decimal\Decimal($value, 40); }
function decimal41(string $value) { return new \Tg\Decimal\Decimal($value, 41); }
function decimal42(string $value) { return new \Tg\Decimal\Decimal($value, 42); }
function decimal43(string $value) { return new \Tg\Decimal\Decimal($value, 43); }
function decimal44(string $value) { return new \Tg\Decimal\Decimal($value, 44); }
function decimal45(string $value) { return new \Tg\Decimal\Decimal($value, 45); }
function decimal46(string $value) { return new \Tg\Decimal\Decimal($value, 46); }
function decimal47(string $value) { return new \Tg\Decimal\Decimal($value, 47); }
function decimal48(string $value) { return new \Tg\Decimal\Decimal($value, 48); }
function decimal49(string $value) { return new \Tg\Decimal\Decimal($value, 49); }
function decimal50(string $value) { return new \Tg\Decimal\Decimal($value, 50); }
function decimal51(string $value) { return new \Tg\Decimal\Decimal($value, 51); }
function decimal52(string $value) { return new \Tg\Decimal\Decimal($value, 52); }
function decimal53(string $value) { return new \Tg\Decimal\Decimal($value, 53); }
function decimal54(string $value) { return new \Tg\Decimal\Decimal($value, 54); }
function decimal55(string $value) { return new \Tg\Decimal\Decimal($value, 55); }
function decimal56(string $value) { return new \Tg\Decimal\Decimal($value, 56); }
function decimal57(string $value) { return new \Tg\Decimal\Decimal($value, 57); }
function decimal58(string $value) { return new \Tg\Decimal\Decimal($value, 58); }
function decimal59(string $value) { return new \Tg\Decimal\Decimal($value, 59); }
function decimal60(string $value) { return new \Tg\Decimal\Decimal($value, 60); }
function decimal61(string $value) { return new \Tg\Decimal\Decimal($value, 61); }
function decimal62(string $value) { return new \Tg\Decimal\Decimal($value, 62); }
function decimal63(string $value) { return new \Tg\Decimal\Decimal($value, 63); }
function decimal64(string $value) { return new \Tg\Decimal\Decimal($value, 64); }
function decimal65(string $value) { return new \Tg\Decimal\Decimal($value, 65); }
function decimal66(string $value) { return new \Tg\Decimal\Decimal($value, 66); }
function decimal67(string $value) { return new \Tg\Decimal\Decimal($value, 67); }
function decimal68(string $value) { return new \Tg\Decimal\Decimal($value, 68); }
function decimal69(string $value) { return new \Tg\Decimal\Decimal($value, 69); }
function decimal70(string $value) { return new \Tg\Decimal\Decimal($value, 70); }
function decimal71(string $value) { return new \Tg\Decimal\Decimal($value, 71); }
function decimal72(string $value) { return new \Tg\Decimal\Decimal($value, 72); }
function decimal73(string $value) { return new \Tg\Decimal\Decimal($value, 73); }
function decimal74(string $value) { return new \Tg\Decimal\Decimal($value, 74); }
function decimal75(string $value) { return new \Tg\Decimal\Decimal($value, 75); }
function decimal76(string $value) { return new \Tg\Decimal\Decimal($value, 76); }
function decimal77(string $value) { return new \Tg\Decimal\Decimal($value, 77); }
function decimal78(string $value) { return new \Tg\Decimal\Decimal($value, 78); }
function decimal79(string $value) { return new \Tg\Decimal\Decimal($value, 79); }
function decimal80(string $value) { return new \Tg\Decimal\Decimal($value, 80); }
function decimal81(string $value) { return new \Tg\Decimal\Decimal($value, 81); }
function decimal82(string $value) { return new \Tg\Decimal\Decimal($value, 82); }
function decimal83(string $value) { return new \Tg\Decimal\Decimal($value, 83); }
function decimal84(string $value) { return new \Tg\Decimal\Decimal($value, 84); }
function decimal85(string $value) { return new \Tg\Decimal\Decimal($value, 85); }
function decimal86(string $value) { return new \Tg\Decimal\Decimal($value, 86); }
function decimal87(string $value) { return new \Tg\Decimal\Decimal($value, 87); }
function decimal88(string $value) { return new \Tg\Decimal\Decimal($value, 88); }
function decimal89(string $value) { return new \Tg\Decimal\Decimal($value, 89); }
function decimal90(string $value) { return new \Tg\Decimal\Decimal($value, 90); }
function decimal91(string $value) { return new \Tg\Decimal\Decimal($value, 91); }
function decimal92(string $value) { return new \Tg\Decimal\Decimal($value, 92); }
function decimal93(string $value) { return new \Tg\Decimal\Decimal($value, 93); }
function decimal94(string $value) { return new \Tg\Decimal\Decimal($value, 94); }
function decimal95(string $value) { return new \Tg\Decimal\Decimal($value, 95); }
function decimal96(string $value) { return new \Tg\Decimal\Decimal($value, 96); }
function decimal97(string $value) { return new \Tg\Decimal\Decimal($value, 97); }
function decimal98(string $value) { return new \Tg\Decimal\Decimal($value, 98); }
function decimal99(string $value) { return new \Tg\Decimal\Decimal($value, 99); }
function decimal100(string $value) { return new \Tg\Decimal\Decimal($value, 100); }
